# Generated by Django 5.0 on 2023-12-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('code_cl', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cl', models.CharField(max_length=50)),
                ('prenom_cl', models.CharField(max_length=50)),
                ('adresse_cl', models.CharField(max_length=100)),
                ('telephone_cl', models.CharField(max_length=50)),
                ('credit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('code_f', models.AutoField(primary_key=True, serialize=False)),
                ('nom_f', models.CharField(max_length=50)),
                ('prenom_f', models.CharField(max_length=50)),
                ('adresse_f', models.CharField(max_length=100)),
                ('telephone_f', models.CharField(max_length=50)),
                ('solde', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('code_P', models.AutoField(primary_key=True, serialize=False)),
                ('designationP', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('num_s', models.AutoField(primary_key=True, serialize=False)),
                ('designation_s', models.CharField(max_length=50)),
                ('qte_s', models.IntegerField()),
                ('prix_achat', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Paiement_credit',
            fields=[
                ('num_pc', models.AutoField(primary_key=True, serialize=False)),
                ('date_pc', models.DateField()),
                ('montant_cl', models.FloatField()),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.client')),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('num_r', models.AutoField(primary_key=True, serialize=False)),
                ('date_r', models.DateField()),
                ('montant_r', models.FloatField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('num_a', models.AutoField(primary_key=True, serialize=False)),
                ('qte_a', models.IntegerField()),
                ('date_a', models.DateField()),
                ('type_Paiement_A', models.CharField(max_length=20)),
                ('montant_A', models.FloatField()),
                ('prix_unitaireHT', models.FloatField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.produit')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_t', models.IntegerField()),
                ('date_t', models.DateField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.centre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('num_v', models.AutoField(primary_key=True, serialize=False)),
                ('qte_v', models.IntegerField()),
                ('date_v', models.DateField()),
                ('type_paiement_v', models.CharField(max_length=20)),
                ('montant_v', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.produit')),
            ],
        ),
    ]
