# Generated by Django 5.0 on 2023-12-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='solde',
            field=models.FloatField(default=0.0),
        ),
    ]
