# Generated by Django 5.0 on 2023-12-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0002_alter_fournisseur_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
    ]
