# Generated by Django 5.0 on 2024-01-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0003_alter_client_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='type_Paiement_A',
            field=models.CharField(choices=[('Entier', 'Entier'), ('Partiel', 'Partiel')], max_length=20),
        ),
    ]
