# Generated by Django 5.0 on 2024-01-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0005_alter_achat_stock_alter_achat_type_paiement_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='prix_achat',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='qte_s',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
