# Generated by Django 5.0 on 2024-01-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0010_alter_vente_type_paiement_v'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfert',
            old_name='stock',
            new_name='produit',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='id',
        ),
        migrations.AddField(
            model_name='transfert',
            name='montant_t',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transfert',
            name='num_t',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
