# Generated by Django 5.0 on 2024-01-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0011_rename_stock_transfert_produit_remove_transfert_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement_credit',
            old_name='Client',
            new_name='client',
        ),
    ]
