# Generated by Django 5.0 on 2024-01-03 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0011_alter_achat_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='stock',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_store.stock'),
        ),
    ]
