# Generated by Django 5.0 on 2024-01-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_store', '0012_alter_achat_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='stock',
        ),
    ]
