# Generated by Django 5.0 on 2023-12-29 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
        ('main_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventecentre',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_store.client'),
        ),
        migrations.AddField(
            model_name='ventecentre',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.produits_centre'),
        ),
    ]
