# Generated by Django 5.0 on 2023-12-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='Code_c',
            new_name='code_c',
        ),
    ]
