# Generated by Django 5.0 on 2024-01-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0007_clientc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventecentre',
            name='type_Paiement_vc',
            field=models.CharField(choices=[('Entier', 'Entier'), ('Partiel', 'Partiel')], default='Entier', max_length=20),
        ),
        migrations.AlterField(
            model_name='ventecentre',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.clientc'),
        ),
    ]
