# Generated by Django 5.0 on 2024-01-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_ventecentre_type_paiement_vc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits_centre',
            name='qte_pc',
            field=models.IntegerField(default=0),
        ),
    ]
