# Generated by Django 5.0 on 2024-01-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0008_ventecentre_type_paiement_vc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produits_centre',
            old_name='Code_pc',
            new_name='code_pc',
        ),
        migrations.AddField(
            model_name='produits_centre',
            name='qte_pc',
            field=models.IntegerField(default=0),
        ),
    ]
