# Generated by Django 5.0 on 2024-01-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_rename_code_pc_produits_centre_code_pc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventecentre',
            name='centre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='center.centre'),
        ),
    ]
