# Generated by Django 5.0 on 2024-01-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_ventecentre_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventecentre',
            name='prix_unitaireVTC',
            field=models.FloatField(default=0),
        ),
    ]
